name: 'Call composite action checkout static versioning'

on:
  push:
  workflow_dispatch:

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: 'Call composite action checkout static versioning'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kyanny-corp-enterprise-cloud-testing/zd-1669617-called-repo-1
          ref: v1
      - uses: ./zd-1669617-called-repo-1/.github/actions
